name = "ITensorNetworkAD"
uuid = "79b97fc6-f224-48a6-bc79-3a561f8ff86d"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org>", "Linjian Ma <lma16@illinois.edu>"]
version = "0.0.1"

[deps]
AutoHOOT = "0bdf4f06-f75d-419a-8d6b-4ad79dc3c0f5"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
ChainRulesCore = "0.10"
Graphs = "1"
ITensors = "0.2"
OptimKit = "0.3"
Reexport = "1"
Zygote = "0.6"
ZygoteRules = "0.2"
julia = "1.3"
